import React,{useEffect,useState} from 'react';
import {collection,getDocs,doc,setDoc} from 'firebase/firestore';
import './access-admin.css';
const labels={p1:'ประถมต้น',p2:'ประถมปลาย',m1:'มัธยมต้น',m2:'มัธยมปลาย'};
const role=d=>d?.canEdit?'editor':d?.isTeacher?'teacher':'viewer';
const roles={viewer:['ดูรายงาน','ดูข้อมูลและรายงานในช่วงชั้นที่เลือก'],teacher:['ครู / ขอแลกคาบ','ใช้งานในบทบาทครูและขอแลกคาบ'],editor:['จัดการตาราง','แก้ไขข้อมูลและจัดตารางในช่วงชั้นที่เลือก']};
const hasAccess=u=>Object.keys(labels).some(k=>u.divisions?.[k]===true);
export default function AccessAdmin({user,db,onBack,refreshPerms}) {
 const [allowed,setAllowed]=useState(false),[users,setUsers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 async function load(){const snap=await getDocs(collection(db,'permissions'));setUsers(snap.docs.filter(d=>!d.id.startsWith('pre_')).map(d=>({...d.data(),uid:d.id})).sort((a,b)=>(a.displayName||a.email||'').localeCompare(b.displayName||b.email||'','th')));}
 useEffect(()=>{let active=true;(async()=>{try{const token=await user?.getIdTokenResult(true);if(!token?.claims.admin)throw Error('บัญชีนี้ไม่มีสิทธิ์ผู้ดูแล');if(active){setAllowed(true);await load();}}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement;const dialog=document.getElementById('access-editor');dialog?.focus();function key(e){if(e.key==='Escape'&&!busy)setSelected(null);if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')];const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[!!selected,busy]);
 async function save(){setBusy(true);setError('');try{await setDoc(doc(db,'permissions',selected.uid),{divisions:selected.divisions},{merge:true});setUsers(list=>list.map(u=>u.uid===selected.uid?{...u,divisions:selected.divisions}:u));setNotice('บันทึกสิทธิ์ของ '+(selected.displayName||selected.email)+' แล้ว');setSelected(null);await refreshPerms();}catch(e){setError('บันทึกสิทธิ์ไม่สำเร็จ: '+e.message);}finally{setBusy(false);}}
 const visible=users.filter(u=>((u.displayName||'')+' '+(u.email||'')).toLowerCase().includes(search.trim().toLowerCase())&&(filter==='all'||filter==='none'&&!hasAccess(u)||u.divisions?.[filter]===true));
 return <main className="access-admin"><header><div><button className="aa-back" onClick={onBack}>← กลับหน้าหลัก</button><h1>จัดการสิทธิ์ผู้ใช้</h1><p>ดูช่วงชั้นและบทบาทของแต่ละคน แล้วเลือกแก้ไขสิทธิ์</p></div><span className="aa-count">{users.length} บัญชี</span></header>
 {notice&&<div className="aa-success" role="status">✓ {notice}</div>}{error&&<div className="aa-error" role="alert">{error}</div>}
 {allowed&&<><div className="aa-toolbar"><input aria-label="ค้นหาผู้ใช้" placeholder="ค้นหาชื่อหรืออีเมล…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="กรองช่วงชั้น" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทุกช่วงชั้น</option><option value="none">ยังไม่กำหนดช่วงชั้น</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><span>พบ {visible.length} บัญชี</span></div><div className="aa-table-wrap"><table><thead><tr><th>ชื่อ / อีเมล</th><th>ช่วงชั้นที่เข้าถึง</th><th>บทบาทตามสิทธิ์</th><th>จัดการ</th></tr></thead><tbody>{visible.map(u=><tr key={u.uid}><td><strong>{u.displayName||'ยังไม่ระบุชื่อ'}</strong><small>{u.email}</small></td><td><div className="aa-tags">{Object.entries(labels).filter(([k])=>u.divisions?.[k]===true).map(([k,v])=><span key={k} className={'aa-tag '+k}>{v}</span>)}{!hasAccess(u)&&<span className="aa-muted">ยังไม่กำหนดช่วงชั้น</span>}</div></td><td>{roles[role(u.divisions)][0]}</td><td><button onClick={()=>{setError('');setSelected({...u,divisions:{...u.divisions}});}}>แก้ไขสิทธิ์</button></td></tr>)}</tbody></table>{!visible.length&&<p className="aa-empty">{loading?'กำลังโหลดบัญชี…':'ไม่พบบัญชีที่ตรงกับการค้นหา'}</p>}</div><p className="aa-help">เพิ่มผู้ใช้: ให้เจ้าของบัญชี Google โรงเรียนเข้าสู่ระบบครั้งแรก แล้วกลับมาเปิดหน้านี้เพื่อกำหนดสิทธิ์ • สิทธิ์ผู้ดูแลระบบจัดการแยกจากบทบาทในตารางนี้</p></>}
 {selected&&<div className="aa-overlay"><section id="access-editor" className="aa-dialog" role="dialog" aria-modal="true" aria-labelledby="aa-title" tabIndex={-1}><h2 id="aa-title">แก้ไขสิทธิ์ผู้ใช้</h2><strong>{selected.displayName||selected.email}</strong><p>{selected.email}</p>{error&&<div role="alert" className="aa-error">{error}</div>}<fieldset disabled={busy}><legend>1. เลือกช่วงชั้นที่เข้าถึงได้</legend><div className="aa-options">{Object.entries(labels).map(([k,v])=><label key={k}><input type="checkbox" checked={selected.divisions[k]===true} onChange={e=>setSelected({...selected,divisions:{...selected.divisions,[k]:e.target.checked}})}/>{v}</label>)}</div></fieldset><fieldset disabled={busy}><legend>2. เลือกบทบาท</legend>{Object.entries(roles).map(([k,[title,desc]])=><label className="aa-role" key={k}><input type="radio" name="access-role" checked={role(selected.divisions)===k} onChange={()=>setSelected({...selected,divisions:{...selected.divisions,canEdit:k==='editor',isTeacher:k==='teacher'}})}/><span><strong>{title}</strong><small>{desc}</small></span></label>)}</fieldset><div className="aa-summary">{hasAccess(selected)?'สิทธิ์นี้ใช้กับ: '+Object.entries(labels).filter(([k])=>selected.divisions[k]).map(([,v])=>v).join(' · '):'ไม่ได้เลือกช่วงชั้น: บัญชีทั่วไปจะเข้าใช้ข้อมูลตารางไม่ได้'}<small>การแก้ไขนี้ไม่เปลี่ยนสิทธิ์ผู้ดูแลระบบ</small></div><footer><button disabled={busy} onClick={()=>setSelected(null)}>ยกเลิก</button><button className="aa-primary" disabled={busy} onClick={save}>{busy?'กำลังบันทึก…':'บันทึกสิทธิ์'}</button></footer></section></div>}
 </main>;
}
