import {uiConfirm,uiPrompt,uiAlert} from './AppQuestion.jsx';
import ColorBadge from './ColorBadge.jsx';
import React,{useState,useEffect,useRef} from 'react';
import {Glyph} from './Workspace.jsx';
export function FileActions({actions=[],label="นำเข้า / ส่งออก"}){return actions.length?<details className="file-actions"><summary><Glyph name="download" size={16}/> {label}</summary><div>{actions.map(([name,action])=><button key={name} onClick={e=>{action();e.currentTarget.closest('details').open=false}}>{name}</button>)}</div></details>:null}
export function ManagementToolbar({label,onAdd,actions,children}){return <div className="management-toolbar"><div>{children}</div><div><FileActions actions={actions}/>{onAdd&&<button className="primary" onClick={onAdd}><Glyph name="plus" size={17}/>{label||'เพิ่มรายการ'}</button>}</div></div>}
export function RecordList({rows,columns,onEdit,onDelete,filters=[],searchText=r=>Object.values(r).filter(v=>typeof v==='string').join(' '),placeholder='ค้นหารายการ…',empty='ยังไม่มีข้อมูล'}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState({}),[page,setPage]=useState(1);
 const found=rows.filter(r=>searchText(r).toLowerCase().includes(query.trim().toLowerCase())&&filters.every(f=>!selected[f.key]||f.match(r,selected[f.key])));
 const totalPages=Math.max(1,Math.ceil(found.length/15)),current=Math.min(page,totalPages);
 return <section className="record-list"><div className="record-filters"><label className="search-box"><Glyph name="search" size={16}/><input aria-label={placeholder} placeholder={placeholder} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label>{filters.map(f=><select aria-label={f.label} key={f.key} value={selected[f.key]||''} onChange={e=>{setSelected({...selected,[f.key]:e.target.value});setPage(1)}}><option value="">{f.label}</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>)}<span>{found.length} รายการ</span></div><div className="record-scroll"><table><thead><tr>{columns.map(c=><th key={c.key} scope="col">{c.label}</th>)}{(onEdit||onDelete)&&<th scope="col">จัดการ</th>}</tr></thead><tbody>{found.slice((current-1)*15,current*15).map(r=><tr key={r.id}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]||'—'}</td>)}{(onEdit||onDelete)&&<td className="record-actions">{onEdit&&<button onClick={()=>onEdit(r)} aria-label={'แก้ไข '+(r.name||r.code||'รายการ')}>แก้ไข</button>}{onDelete&&<button className="danger-text" onClick={()=>onDelete(r)} aria-label={'ลบ '+(r.name||r.code||'รายการ')}>ลบ</button>}</td>}</tr>)}</tbody></table>{!found.length&&<p className="empty-message">{rows.length?'ไม่พบรายการที่ตรงกับตัวกรอง':empty}</p>}</div><footer><span>{found.length?`${(current-1)*15+1}–${Math.min(current*15,found.length)} จาก ${found.length}`:'ไม่มีรายการ'}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>ก่อนหน้า</button><span>{current} / {totalPages}</span><button disabled={current===totalPages} onClick={()=>setPage(current+1)}>ถัดไป</button></div></footer></section>
}
export function EditDialog({title,onClose,onSave,children}){
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('input,select,button')?.focus();return()=>previous?.focus?.()},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form ref={ref} role="dialog" aria-modal="true" aria-label={title} className="modern-modal" onSubmit={e=>{e.preventDefault();onSave()}} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=[...ref.current.querySelectorAll('input,select,textarea,button')].filter(x=>!x.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header><h2>{title}</h2><button type="button" aria-label="ปิด" onClick={onClose}><Glyph name="close"/></button></header><div className="form-grid">{children}</div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>ยกเลิก</button><button className="primary" type="submit">บันทึก</button></div></form></div>
}
export function LevelsManager({S,U,st,divisions,actions}){
 const [tab,setTab]=useState('rooms'),[edit,setEdit]=useState(null);
 const open=(kind,item)=>setEdit({kind,id:item?.id||'',name:item?.name||'',levelId:item?.levelId||S.levels[0]?.id||'',planId:item?.planId||'',divisionId:item?.divisionId||'m2',assemblyDay:item?.assemblyDay||''});
 const save=()=>{const key=edit.kind==='rooms'?'rooms':'levels',setter=edit.kind==='rooms'?U.setRooms:U.setLevels;const name=edit.name.trim();if(!name){st('กรุณากรอกชื่อ','error');return}if(key==='rooms'&&!edit.levelId){st('เลือกระดับชั้นก่อน','error');return}if(S[key].some(r=>r.id!==edit.id&&r.name.trim()===name)){st('ชื่อนี้มีอยู่แล้ว','error');return}const data=key==='rooms'?{name,levelId:edit.levelId,planId:edit.planId}:{name,divisionId:edit.divisionId,assemblyDay:edit.assemblyDay};setter(prev=>edit.id?prev.map(x=>x.id===edit.id?{...x,...data}:x):[...prev,{id:crypto.randomUUID().replaceAll('-',''),...data}]);setEdit(null);st('บันทึกแล้ว')};
 const remove=async (r)=>{if(tab==='levels'&&(S.rooms.some(x=>x.levelId===r.id)||S.subjects.some(x=>x.levelId===r.id))){st('ระดับชั้นนี้ยังมีห้องเรียนหรือวิชา กรุณาย้ายข้อมูลก่อนลบ','error');return}if(tab==='rooms'&&(S.assigns.some(x=>x.roomIds?.includes(r.id))||Object.keys(S.schedule).some(k=>k.startsWith(r.id+'_')))){st('ห้องนี้ยังมีงานมอบหมายหรือตารางสอน กรุณาย้ายข้อมูลก่อนลบ','error');return}if(!await uiConfirm('ลบ '+r.name+'?'))return;(tab==='rooms'?U.setRooms:U.setLevels)(prev=>prev.filter(x=>x.id!==r.id));st('ลบแล้ว','warning')};
 const roomColumns=[{key:'name',label:'ห้องเรียน',render:r=><strong>{r.name}</strong>},{key:'level',label:'ระดับชั้น',render:r=><ColorBadge item={S.levels.find(l=>l.id===r.levelId)} kind="level"/>},{key:'plan',label:'แผนการเรียน',render:r=>S.plans.find(p=>p.id===r.planId)?.name||'ยังไม่ระบุ'},{key:'assigns',label:'งานมอบหมาย',render:r=>S.assigns.filter(a=>a.roomIds?.includes(r.id)).length+' รายการ'}];
 const levelColumns=[{key:'name',label:'ระดับชั้น',render:r=><ColorBadge item={r} kind="level"/>},{key:'division',label:'ช่วงชั้น / เวลาคาบ',render:r=>divisions.find(d=>d.id===r.divisionId)?.name||'ยังไม่ระบุ'},{key:'assembly',label:'วันเข้าหอประชุม',render:r=>r.assemblyDay||'ไม่มี'},{key:'rooms',label:'จำนวนห้อง',render:r=>S.rooms.filter(x=>x.levelId===r.id).length}];
 return <><div className="task-tabs"><button className={tab==='rooms'?'selected':''} onClick={()=>setTab('rooms')}>ห้องเรียน <span>{S.rooms.length}</span></button><button className={tab==='levels'?'selected':''} onClick={()=>setTab('levels')}>ระดับชั้นและเวลาคาบ <span>{S.levels.length}</span></button></div><ManagementToolbar label={tab==='rooms'?'เพิ่มห้องเรียน':'เพิ่มระดับชั้น'} onAdd={()=>open(tab)} actions={actions}><p className="context-note">{tab==='rooms'?'ตรวจห้องและแผนการเรียน แก้ไขได้จากแต่ละแถว':'กำหนดช่วงชั้นและวันเข้าหอประชุมผ่านปุ่มแก้ไข'}</p></ManagementToolbar><RecordList key={tab} rows={tab==='rooms'?S.rooms:S.levels} columns={tab==='rooms'?roomColumns:levelColumns} placeholder={tab==='rooms'?'ค้นหาห้องเรียน…':'ค้นหาระดับชั้น…'} filters={tab==='rooms'?[{key:'level',label:'ทุกระดับชั้น',options:S.levels.map(l=>({value:l.id,label:l.name})),match:(r,v)=>r.levelId===v}]:[]} onEdit={r=>open(tab,r)} onDelete={remove}/>{edit&&<EditDialog title={(edit.id?'แก้ไข':'เพิ่ม')+(edit.kind==='rooms'?'ห้องเรียน':'ระดับชั้น')} onClose={()=>setEdit(null)} onSave={save}><label className="wide">ชื่อ{edit.kind==='rooms'?'ห้องเรียน':'ระดับชั้น'}<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label>{edit.kind==='rooms'?<><label>ระดับชั้น<select required value={edit.levelId} onChange={e=>setEdit({...edit,levelId:e.target.value})}><option value="">เลือกระดับชั้น</option>{S.levels.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>แผนการเรียน<select value={edit.planId} onChange={e=>setEdit({...edit,planId:e.target.value})}><option value="">ไม่ระบุ</option>{S.plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>:<><label>ช่วงชั้น<select value={edit.divisionId} onChange={e=>setEdit({...edit,divisionId:e.target.value})}>{divisions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>วันเข้าหอประชุม<select value={edit.assemblyDay} onChange={e=>setEdit({...edit,assemblyDay:e.target.value})}><option value="">ไม่มี</option>{['จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์'].map(d=><option key={d}>{d}</option>)}</select></label><p className="wide context-note">ช่วงชั้นใช้กำหนดเวลาคาบ 6–7 ส่วนหอประชุมเป็นช่วง 08.00–08.30 น.</p></>}</EditDialog>}</>;
}
