import {uiConfirm,uiPrompt,uiAlert} from './AppQuestion.jsx';
import React,{useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {makeTemplate,migrateLegacy,printDocument,templateIssues,PRINT_DAYS,FIELDS} from './print-model.mjs';
import ColorBadge from './ColorBadge.jsx';
import './print-studio.css';
const KEY='dara_preview_printStudio_v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}};
const clone=x=>JSON.parse(JSON.stringify(x));
function Field({label,children}){return <label className="studio-field"><span>{label}</span>{children}</label>}
export default function PrintStudio({open,onClose,S,ay,sh,getPeriodCfg}){
 const [saved,setSaved]=useState(read),[scope,setScope]=useState(S.levels[0]?.id||'teacher'),[target,setTarget]=useState(''),[tab,setTab]=useState('columns'),[notice,setNotice]=useState(''),[copyId,setCopyId]=useState(''),[zoom,setZoom]=useState(85);
 const root=useRef(null),importRef=useRef(null),previous=useRef(null);
 const level=S.levels.find(l=>l.id===scope),type=scope==='teacher'?'teacher':'room',base=makeTemplate(level,getPeriodCfg(level?.divisionId)),layout=saved[scope]||base;
 const targets=type==='teacher'?S.teachers:S.rooms.filter(r=>r.levelId===scope),id=targets.some(r=>r.id===target)?target:targets[0]?.id||'';
 const issues=id?templateIssues(layout,S,type,id):['ยังไม่มี'+(type==='room'?'ห้องเรียนในระดับชั้นนี้':'ครู')];
 const html=printDocument(id?[{template:layout,type,id}]:[],S,ay,sh);
 useEffect(()=>{if(!open)return;previous.current=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.querySelector('button')?.focus();return()=>{document.body.style.overflow=old;previous.current?.focus?.()}},[open]);
 const store=next=>{try{localStorage.setItem(KEY,JSON.stringify(next));setSaved(next);setNotice('บันทึกแบบพิมพ์ในเบราว์เซอร์นี้แล้ว')}catch{setNotice('บันทึกไม่สำเร็จ พื้นที่เบราว์เซอร์อาจเต็ม กรุณาส่งออกแบบพิมพ์');setSaved(next)}};
 const update=(key,value)=>store({...saved,[scope]:{...layout,[key]:value}});
 const column=(i,key,value)=>update('columns',layout.columns.map((c,j)=>j===i?{...c,[key]:value}:c));
 const move=(key,i,dir)=>{const arr=[...layout[key]],j=i+dir;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];update(key,arr)};
 const addColumn=()=>update('columns',[...layout.columns,{id:crypto.randomUUID(),type:'custom',label:'กิจกรรม',time:'',text:'',days:[],width:65,show:true}]);
 const getLayout=l=>saved[l.id]||makeTemplate(l,getPeriodCfg(l.divisionId));
 const print=batch=>{
  const pages=batch?targets.map(r=>({template:layout,type,id:r.id})):[{template:layout,type,id}];
  const errors=pages.flatMap(p=>templateIssues(p.template,S,p.type,p.id));if(errors.length){setNotice([...new Set(errors)].join(' · '));return}
  const w=window.open('','_blank');if(!w){setNotice('เบราว์เซอร์ปิดกั้นหน้าต่างพิมพ์ กรุณาอนุญาตป๊อปอัปแล้วลองอีกครั้ง');return}w.document.open();w.document.write(printDocument(pages,S,ay,sh));w.document.close();
  const ready=()=>{const images=[...w.document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve}));Promise.all([w.document.fonts?.ready,...images]).then(()=>{w.focus();w.print()})};if(w.document.readyState==='complete')ready();else w.addEventListener('load',ready,{once:true});
 };
 const download=()=>{const data={version:1,templates:{...saved,[scope]:layout}},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='dara-print-templates.json';a.click();URL.revokeObjectURL(url)};
 const importFile=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const raw=JSON.parse(await file.text());if(raw.version!==1||!raw.templates||Object.values(raw.templates).some(t=>!Array.isArray(t.columns)||!Array.isArray(t.days)||!t.days.every(d=>PRINT_DAYS.includes(d))||!Array.isArray(t.fields)||!t.fields.every(f=>FIELDS[f])||t.columns.some(c=>!c||!['period','break','assembly','homeroom','custom'].includes(c.type))))throw Error();store({...saved,...raw.templates});setNotice('นำเข้าแบบพิมพ์แล้ว')}catch{setNotice('ไฟล์แบบพิมพ์ไม่ถูกต้อง กรุณาใช้ไฟล์ที่ส่งออกจากหน้านี้')}};
 if(!open)return null;
 return createPortal(<div ref={root} className="print-studio" role="dialog" aria-modal="true" aria-label="ออกแบบตารางพิมพ์" onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=[...root.current.querySelectorAll('button,input,select,textarea,a')].filter(n=>!n.disabled&&n.getClientRects().length),a=items[0],b=items.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b?.focus()}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a?.focus()}}}}>
  <header className="studio-header"><div><span className="studio-eyebrow">DARA / PRINT STUDIO</span><h1>ออกแบบตารางพิมพ์</h1><p>แต่ละระดับชั้นมีแบบพิมพ์ของตัวเอง · ปรับแล้วบันทึกอัตโนมัติ</p></div><div className="studio-buttons"><button onClick={download}>ส่งออกแบบพิมพ์</button><button aria-label="ปิดพื้นที่ออกแบบ" onClick={onClose}>ปิด ✕</button></div></header>
  <div className="studio-body"><aside className="studio-settings">
   <section className="studio-scope"><Field label="แบบพิมพ์ที่ต้องการแก้ไข"><select value={scope} onChange={e=>{setScope(e.target.value);setTarget('');setNotice('');setCopyId('')}}>{S.levels.map(l=><option key={l.id} value={l.id}>ตารางเรียน {l.name}</option>)}<option value="teacher">ตารางสอนครู</option></select></Field>{level&&<ColorBadge item={level} kind="level"/>}<p>การตั้งค่าที่นี่เปลี่ยนเฉพาะหน้ากระดาษ ไม่เปลี่ยนคาบที่จัดไว้</p></section>
   <nav className="studio-tabs" aria-label="การตั้งค่าแบบพิมพ์">{[['columns','คาบ / กิจกรรม'],['content','ข้อมูลในช่อง'],['paper','หน้ากระดาษ'],['templates','จัดการแบบ']].map(([key,label])=><button key={key} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
   <div className="studio-controls">
    {tab==='columns'&&<><h2>วันและโครงสร้างตาราง</h2><div className="studio-days">{PRINT_DAYS.map(d=><label key={d}><input type="checkbox" checked={layout.days.includes(d)} onChange={e=>update('days',PRINT_DAYS.filter(x=>x===d?e.target.checked:layout.days.includes(x)))}/>{d}</label>)}</div><p className="studio-help">หมายเลขคาบเชื่อมกับข้อมูลจริง ส่วนชื่อและเวลาแก้เพื่อจัดหน้าพิมพ์ได้</p>{layout.columns.map((c,i)=><details className="studio-column" key={c.id}><summary><input aria-label={'แสดง '+c.label} type="checkbox" checked={c.show} onClick={e=>e.stopPropagation()} onChange={e=>column(i,'show',e.target.checked)}/><span>{c.label||'ไม่มีชื่อ'}<small>{c.type==='period'?'ข้อมูลคาบ '+c.periodId:'กิจกรรม'} · {c.time||'ไม่ระบุเวลา'}</small></span><span>⌄</span></summary><div className="studio-column-body"><Field label="ประเภท"><select value={c.type} onChange={e=>column(i,'type',e.target.value)}>{[['period','คาบเรียน'],['break','พัก'],['assembly','กิจกรรมเช้า / หอประชุม'],['homeroom','โฮมรูม'],['custom','กิจกรรมอื่น']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="ชื่อคอลัมน์"><input value={c.label} onChange={e=>column(i,'label',e.target.value)}/></Field>{c.type==='period'&&<Field label="ดึงข้อมูลจากคาบที่"><input type="number" min="1" max="20" value={c.periodId||1} onChange={e=>column(i,'periodId',Number(e.target.value))}/></Field>}<Field label="เวลาที่แสดง"><input placeholder="08.30–09.20" value={c.time||''} onChange={e=>column(i,'time',e.target.value)}/></Field><Field label="ความกว้างสัมพัทธ์"><input type="number" min="25" max="250" value={c.width} onChange={e=>column(i,'width',Number(e.target.value))}/></Field>{c.type!=='period'&&<><Field label="ข้อความในช่อง"><input value={c.text||''} onChange={e=>column(i,'text',e.target.value)} placeholder="ใช้ชื่อคอลัมน์ถ้าเว้นว่าง"/></Field><Field label="แสดงกิจกรรมในวัน"><select value={c.days?.[0]||''} onChange={e=>column(i,'days',e.target.value?[e.target.value]:[])}><option value="">ทุกวัน</option>{layout.days.map(d=><option key={d}>{d}</option>)}</select></Field></>}<div className="studio-buttons"><button disabled={!i} onClick={()=>move('columns',i,-1)}>← เลื่อนก่อน</button><button disabled={i===layout.columns.length-1} onClick={()=>move('columns',i,1)}>เลื่อนหลัง →</button><button onClick={()=>update('columns',layout.columns.filter((_,j)=>j!==i))}>ลบ</button></div></div></details>)}<button className="studio-add" onClick={addColumn}>+ เพิ่มคาบ / พัก / กิจกรรม</button></>}
    {tab==='content'&&<><h2>ข้อมูลในแต่ละช่อง</h2><p className="studio-help">เรียงจากบนลงล่าง แสดงครบทุกวิชาและครูร่วมในคาบนั้น</p>{layout.fields.map((f,i)=><div className="studio-content-row" key={i}><select aria-label={'ข้อมูลบรรทัด '+(i+1)} value={f} onChange={e=>update('fields',layout.fields.map((x,j)=>j===i?e.target.value:x))}>{Object.entries(FIELDS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button disabled={!i} aria-label="เลื่อนขึ้น" onClick={()=>move('fields',i,-1)}>↑</button><button disabled={i===layout.fields.length-1} aria-label="เลื่อนลง" onClick={()=>move('fields',i,1)}>↓</button><button aria-label="ลบบรรทัด" onClick={()=>update('fields',layout.fields.filter((_,j)=>j!==i))}>×</button></div>)}<button className="studio-add" onClick={()=>update('fields',[...layout.fields,'subject_code'])}>+ เพิ่มบรรทัด</button>{layout.fields.includes('custom_text')&&<Field label="ข้อความกำหนดเอง"><input value={layout.customText||''} onChange={e=>update('customText',e.target.value)}/></Field>}<Field label="สีในตาราง"><select value={layout.colored?'color':'mono'} onChange={e=>update('colored',e.target.value==='color')}><option value="color">สีอ่อนตามกลุ่มสาระ</option><option value="mono">ขาวดำ / ประหยัดหมึก</option></select></Field></>}
    {tab==='paper'&&<><h2>กระดาษและหัวตาราง</h2><div className="studio-grid"><Field label="กระดาษ"><select value={layout.paper} onChange={e=>update('paper',e.target.value)}>{['A4','A3','Letter'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="แนวกระดาษ"><select value={layout.orientation} onChange={e=>update('orientation',e.target.value)}><option value="landscape">แนวนอน</option><option value="portrait">แนวตั้ง</option></select></Field>{[['margin','ขอบกระดาษ (มม.)',4,30],['fontSize','ขนาดอักษร (px)',8,24],['rowHeight','ความสูงแถวขั้นต่ำ (px)',30,180]].map(([k,l,min,max])=><Field label={l} key={k}><input type="number" min={min} max={max} value={layout[k]} onChange={e=>update(k,Number(e.target.value))}/></Field>)}</div><Field label="หัวเรื่อง (ว่าง = ชื่อห้อง / ครูอัตโนมัติ)"><input value={layout.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="บรรทัดรอง (ว่าง = โรงเรียน / ปีการศึกษา)"><input value={layout.subtitle} onChange={e=>update('subtitle',e.target.value)}/></Field><label><input type="checkbox" checked={layout.showLogo} onChange={e=>update('showLogo',e.target.checked)}/> แสดงตราโรงเรียนที่ตั้งค่าไว้</label><Field label="ท้ายกระดาษ / ผู้ลงนาม"><textarea rows="4" value={layout.footer} onChange={e=>update('footer',e.target.value)}/></Field></>}
    {tab==='templates'&&<><h2>แบบพิมพ์ของระดับชั้นนี้</h2><Field label="ชื่อแบบพิมพ์"><input value={layout.name} onChange={e=>update('name',e.target.value)}/></Field><p className="studio-help">แต่ละระดับชั้นบันทึกแยกกัน คัดลอกแล้วปรับต่อได้โดยไม่กระทบต้นแบบ</p><Field label="คัดลอกจาก"><select value={copyId} onChange={e=>setCopyId(e.target.value)}><option value="">เลือกต้นแบบ</option>{S.levels.filter(l=>l.id!==scope).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><button disabled={!copyId} onClick={()=>{store({...saved,[scope]:{...clone(getLayout(S.levels.find(l=>l.id===copyId))),name:layout.name}});setCopyId('')}}>คัดลอกมาใช้กับแบบนี้</button><button className="studio-add" onClick={async ()=>{if(await uiConfirm('คืนค่าแบบพิมพ์นี้ตามเวลาคาบของระดับชั้น?'))store({...saved,[scope]:base})}}>คืนค่าเริ่มต้นตามระดับชั้น</button><hr/><button onClick={()=>importRef.current.click()}>นำเข้าไฟล์แบบพิมพ์</button><input hidden type="file" ref={importRef} accept=".json" onChange={importFile}/><p className="studio-help">ส่งออกไฟล์เพื่อสำรองหรือย้ายเครื่อง แบบพิมพ์เก็บแยกจากข้อมูลตารางสอน</p><details><summary>นำแบบจาก Print Designer เดิมมาใช้</summary>{(()=>{let old={};try{old=JSON.parse(localStorage.getItem('dara_preview_pdLayouts2'))||{}}catch{}return Object.keys(old).length?Object.entries(old).map(([name,t])=><button key={name} onClick={()=>store({...saved,[scope]:{...migrateLegacy(t,base),name}})}>{name}</button>):<p>ไม่มีแบบพิมพ์เดิมที่บันทึกไว้</p>})()}</details></>}
   </div><div className="studio-save" role="status">{notice||'พร้อมแก้ไข · เก็บแบบพิมพ์แยกแต่ละระดับชั้น'}</div>
  </aside><main className="studio-preview"><div className="studio-preview-toolbar"><Field label="ตัวอย่างจากข้อมูลจริง"><select value={id} onChange={e=>setTarget(e.target.value)}>{!targets.length&&<option value="">ไม่มีข้อมูล</option>}{targets.map(r=><option key={r.id} value={r.id}>{type==='room'?r.name:`${r.firstName} ${r.lastName}`}</option>)}</select></Field><Field label="ขนาดตัวอย่าง"><select value={zoom} onChange={e=>setZoom(+e.target.value)}>{[50,65,85,100,125].map(z=><option value={z} key={z}>{z}%</option>)}</select></Field><div className="studio-buttons"><button disabled={!id||!!issues.length} onClick={()=>print(false)}>พิมพ์รายการนี้ / PDF</button><button className="studio-primary" disabled={!targets.length} onClick={()=>print(true)}>พิมพ์{type==='room'?'ระดับชั้นนี้':'ครูทั้งหมด'} ({targets.length})</button></div></div>
   {!!issues.length&&<div className="studio-warning" role="alert">{issues.join(' · ')}</div>}<div className="studio-canvas">{id?<iframe title="ตัวอย่างตารางพิมพ์จากข้อมูลจริง" sandbox="allow-same-origin" srcDoc={html} style={{width:layout.orientation==='portrait'?'850px':'1250px',height:'1050px',zoom:zoom/100}}/>:<div className="studio-empty">เพิ่มข้อมูลห้องเรียนหรือครูก่อนเริ่มดูตัวอย่าง</div>}</div><footer className="studio-preview-note">ตัวอย่างและงานพิมพ์ใช้ข้อมูลชุดเดียวกัน · ตรวจจำนวนหน้าในหน้าต่างพิมพ์ก่อนบันทึก PDF · ครูที่สอนข้ามช่วงชั้นควรเลือกแสดง “เวลา” ในช่อง</footer>
  </main></div>
 </div>,document.body);
}
