import React,{useState} from 'react';
export default function ReportLauncher({mode,S,actions}){
 const [target,setTarget]=useState('teacher'),[scope,setScope]=useState('all'),[id,setId]=useState('');
 const people=target==='teacher'?S.teachers.map(t=>({id:t.id,name:`${t.prefix||''}${t.firstName} ${t.lastName}`})):target==='level'?S.levels:S.rooms;
 const run=()=>{if(mode==='excel'){if(target==='status')return actions.status();if(target==='teacher')return scope==='all'?actions.teacherExcelAll():actions.teacherExcel(id);return scope==='all'?actions.roomExcelAll():actions.roomExcel(id)}if(target==='dept')return actions.deptPDF();if(target==='level')return actions.levelPDF(id);if(target==='teacher')return scope==='all'?actions.teacherPDFAll():actions.teacherPDF(id);return scope==='all'?actions.roomPDFAll():actions.roomPDF(id)};
 if(mode==='backup')return <div className="backup-layout"><section><h3>สำรองข้อมูล</h3><p>ดาวน์โหลดไฟล์ JSON เก็บไว้ก่อนเปลี่ยนข้อมูลจำนวนมาก</p><button className="primary" onClick={actions.backup}>ดาวน์โหลดข้อมูลสำรอง</button></section><section><h3>คืนค่าจากไฟล์สำรอง</h3><p>ข้อมูลจากไฟล์จะนำมาทับหรือรวมกับข้อมูลปัจจุบัน ควรสำรองก่อนทุกครั้ง</p><button className="secondary" onClick={actions.restore}>เลือกไฟล์เพื่อคืนค่า</button></section></div>;
 const needsId=scope==='single'||target==='level';
 return <section className="report-launcher"><div><h3>{mode==='excel'?'ดาวน์โหลดตารางและรายงาน':'พิมพ์ตารางสอน'}</h3><p>เลือกรายการและขอบเขตที่ต้องการ</p></div><div className="report-fields"><label>ข้อมูลที่ต้องการ<select value={target} onChange={e=>{setTarget(e.target.value);setId('');setScope('all')}}><option value="teacher">ตารางสอนครู</option><option value="room">ตารางเรียนห้อง</option>{mode==='print'?<><option value="dept">ตารางรวมกลุ่มสาระ</option><option value="level">ตารางรวมระดับชั้น</option></>:<option value="status">รายงานสถานะ</option>}</select></label>{['teacher','room'].includes(target)&&<label>ขอบเขต<select value={scope} onChange={e=>{setScope(e.target.value);setId('')}}><option value="all">ทั้งหมด</option><option value="single">เลือกเฉพาะราย{target==='teacher'?'คน':'ห้อง'}</option></select></label>}{needsId&&<label>{target==='teacher'?'ครู':target==='level'?'ระดับชั้น':'ห้องเรียน'}<select value={id} onChange={e=>setId(e.target.value)}><option value="">เลือกรายการ</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}</div><div className="report-submit"><span>{mode==='excel'?'ไฟล์ Excel (.xlsx)':'เปิดหน้าต่างพิมพ์ / บันทึกเป็น PDF'}</span><button className="primary" disabled={needsId&&!id} onClick={run}>{mode==='excel'?'ดาวน์โหลด Excel':'เปิดตารางสำหรับพิมพ์'}</button></div><details className="advanced-options"><summary>รูปแบบและตัวเลือกเพิ่มเติม</summary><div>{mode==='print'?<><button className="secondary" onClick={actions.teacherTwo}>จัดหน้าครู 2 คน / หน้า</button><button className="secondary" onClick={actions.roomLayout}>เลือกห้องและรูปแบบกระดาษ</button></>:<button className="secondary" onClick={actions.roomExcelChoose}>เลือกหลายห้องสำหรับ Excel</button>}</div></details></section>;
}
