import {esc} from './print-model.mjs';
export const WEEK=['อาทิตย์','จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์'];
export function datesBetween(from,to=from){if(!/^\d{4}-\d{2}-\d{2}$/.test(from||'')||!/^\d{4}-\d{2}-\d{2}$/.test(to||''))return [];const a=new Date(from+'T12:00:00Z'),b=new Date(to+'T12:00:00Z'),diff=(b-a)/86400000;if(!Number.isFinite(diff)||diff<0||diff>30)return [];return Array.from({length:diff+1},(_,i)=>{const d=new Date(+a+i*86400000);return {date:d.toISOString().slice(0,10),day:WEEK[d.getUTCDay()]}}).filter(d=>!['เสาร์','อาทิตย์'].includes(d.day))}
export function lessonList(S,teacherId,day){const out=[];Object.entries(S.schedule||{}).forEach(([key,entries])=>{const a=key.split('_'),pid=Number(a.pop()),d=a.pop(),rid=a.join('_');if(d!==day)return;(entries||[]).forEach(e=>{const co=e.coTeacherIds?.length?e.coTeacherIds:e.coTeacherId?[e.coTeacherId]:[];if(![e.teacherId,...co].includes(teacherId))return;const room=S.rooms.find(r=>r.id===rid),subject=S.subjects.find(s=>s.id===e.subjectId),time=S.periodConfigs?.[rid]?.periods.find(p=>p.id===pid)?.time||S.defaultPeriods.find(p=>p.id===pid)?.time;out.push({...e,coTeacherIds:co,key,roomId:rid,roomName:room?.name||'ไม่พบห้อง',subjectName:subject?.name||'ไม่พบวิชา',departmentId:subject?.departmentId,day,period:pid,time})})});return out}
const minutes=time=>{const m=String(time||'').match(/(\d{1,2})[.:](\d{2})\D+(\d{1,2})[.:](\d{2})/);return m?[+m[1]*60 + +m[2],+m[3]*60 + +m[4]]:null};
export const overlaps=(a,b)=>{const x=minutes(a.time),y=minutes(b.time);return x&&y?x[0]<y[1]&&y[0]<x[1]:a.period===b.period};
export function freeReasons(S,tid,slot){const t=S.teachers.find(t=>t.id===tid);if(!t)return ['ไม่พบครู'];const reasons=[];if(lessonList(S,tid,slot.day).some(e=>overlaps(e,slot)))reasons.push('มีคาบสอนทับเวลา');const blocked=[];(t.personalLocks||[]).forEach(l=>{if(l.day===slot.day)(l.periods||[]).forEach(p=>blocked.push({p,label:l.reason||'ล็อกส่วนตัว'}))});(t.specialRoles||[]).forEach(id=>(S.roles.find(r=>r.id===id)?.blocked||[]).forEach(l=>{if(l.day===slot.day)(l.periods||[]).forEach(p=>blocked.push({p,label:'หน้าที่พิเศษ'}))}));(S.meetings||[]).forEach(m=>{if(m.type==='custom'){(m.slots||[]).filter(s=>s.day===slot.day).forEach(s=>blocked.push({p:s.period,label:m.name||'กิจกรรมโรงเรียน'}));return}if(m.teacherId?m.teacherId===tid:!m.departmentId||m.departmentId==='all'||m.departmentId===t.departmentId){if(m.day===slot.day)(m.periods||[]).forEach(p=>blocked.push({p,label:m.name||'ประชุม / กิจกรรม'}))}});const configs=S.teacherPeriods?.[tid]||[S.defaultPeriods];for(const b of blocked)if(configs.some(ps=>overlaps({period:b.p,time:ps.find(p=>p.id===b.p)?.time},slot)))reasons.push(b.label);return [...new Set(reasons)]}
export const slotKey=s=>[s.date,s.key,s.id||s.subjectId].join('|');
export function requestedSlots(S,teacherId,from,to){return datesBetween(from,to||from).flatMap(d=>lessonList(S,teacherId,d.day).map(e=>({...e,date:d.date})));}
export function findCandidates(S,tid,slot,mode,absence){
 return S.teachers.filter(t=>t.id!==tid&&!freeReasons(S,t.id,slot).length).map(t=>{const sameSubject=S.assigns.some(a=>a.teacherId===t.id&&a.subjectId===slot.subjectId),sameDept=t.departmentId===slot.departmentId,sameRoom=S.assigns.some(a=>a.teacherId===t.id&&a.roomIds?.includes(slot.roomId));
 const load=new Set(WEEK.flatMap(day=>lessonList(S,t.id,day).map(e=>day+'_'+e.period))).size,returns=[];
 if(mode==='swap'){
  const anchor=new Date(slot.date+'T12:00:00Z');for(let n=-14;n<=28;n++){const date=new Date(+anchor+n*86400000).toISOString().slice(0,10);if(n===0||absence.some(d=>d.date===date))continue;const day=WEEK[new Date(date+'T12:00:00Z').getUTCDay()];
  lessonList(S,t.id,day).filter(e=>e.roomId===slot.roomId&&!S.locks?.[e.key]&&!e.coTeacherIds.length&&e.teacherId===t.id&&!freeReasons(S,tid,e).length&&(S.schedule[e.key]||[]).length===1).forEach(e=>returns.push({...e,date}));}
 }
 return {teacher:t,load,reason:sameSubject?'มีงานมอบหมายวิชานี้':sameDept?'กลุ่มสาระเดียวกัน':sameRoom?'สอนห้องนี้อยู่แล้ว':'ว่างตรงเวลา · ต้องตรวจความเหมาะสม',rank:(sameSubject?100:sameDept?60:sameRoom?30:0)-load,returns};
 }).filter(c=>mode==='cover'||c.returns.length).sort((a,b)=>b.rank-a.rank);
}
export function proposalIssues(S,teacherId,proposals,mode,absence){const errors=[],bookings=[];for(const p of proposals){const {slot,candidate,back}=p,t=candidate?.teacher;if(!t){errors.push('ยังไม่ได้เลือกครู');continue}if(freeReasons(S,t.id,slot).length)errors.push('ครูสอนแทนไม่ว่างแล้ว');if(!lessonList(S,teacherId,slot.day).some(e=>e.key===slot.key&&e.id===slot.id))errors.push('ตารางต้นทางเปลี่ยนแล้ว');if(mode==='swap'&&(slot.coTeacherIds.length||(S.schedule[slot.key]||[]).length>1||S.locks?.[slot.key]))errors.push('คาบร่วม / คาบล็อก ต้องตรวจและจัดการเป็นกลุ่มก่อนแลก');bookings.push({teacher:t.id,...slot});if(mode==='swap'){if(!back){errors.push('ยังไม่ได้เลือกคาบสอนคืน');continue}if(!returnDateAllowed(slot.date,back.date))errors.push('วันสอนคืนต้องอยู่ก่อนวันแลกไม่เกิน 14 วัน หรือหลังไม่เกิน 28 วัน');if(absence.some(d=>d.date===back.date))errors.push('คาบสอนคืนอยู่ในช่วงลา');if(freeReasons(S,teacherId,back).length||S.locks?.[back.key])errors.push('คาบสอนคืนไม่ว่างหรือถูกล็อก');bookings.push({teacher:teacherId,...back});}}
 bookings.forEach((a,i)=>bookings.slice(i+1).forEach(b=>{if(a.date===b.date&&overlaps(a,b)&&(a.teacher===b.teacher||a.roomId===b.roomId))errors.push('รายการที่เลือกชนกันเอง: ครูหรือห้องซ้ำเวลา')}));return [...new Set(errors)]}
export {proposalHTML} from './swap-form.mjs';

export function returnDateAllowed(anchor,date){const n=(new Date(date+'T12:00:00Z')-new Date(anchor+'T12:00:00Z'))/86400000;return Number.isInteger(n)&&n>=-14&&n<=28&&n!==0;}
