import TeacherPicker from './TeacherPicker.jsx';
import './swap-mobile.css';
import DateField from './DateField.jsx';
import {SevenPicker,LoadImpact,ReturnCards,thaiDate} from './SwapCards.jsx';
import React,{useState,useRef} from 'react';
import {datesBetween,requestedSlots,slotKey,findCandidates,proposalIssues,proposalHTML} from './swap-model.mjs';
import ColorBadge from './ColorBadge.jsx';

export default function SwapWorkbench({S,st,ay,sh}){
 const mode='swap';
 const [step,setStep]=useState(1),[expanded,setExpanded]=useState('');const top=useRef(null);
 const goStep=n=>{setStep(n);requestAnimationFrame(()=>{top.current?.scrollIntoView({block:'start',behavior:'smooth'});top.current?.focus({preventScroll:true})})};
 const [dailyLimit,setDailyLimit]=useState(6);
 const [teacher,setTeacher]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[reason,setReason]=useState('ติดธุระ'),[picked,setPicked]=useState([]),[active,setActive]=useState(''),[selected,setSelected]=useState({}),[searched,setSearched]=useState(false),[snapshot,setSnapshot]=useState(''),[query,setQuery]=useState('');
 const signature=JSON.stringify([S.schedule,S.teachers,S.meetings,S.locks,S.assigns,S.periodConfigs,S.subjects,S.rooms,S.roles]),stale=searched&&signature!==snapshot;
 const dates=datesBetween(from,to||from),slots=requestedSlots(S,teacher,from,to),chosen=slots.filter(s=>picked.includes(slotKey(s))),current=chosen.find(s=>slotKey(s)===active)||chosen[0];
 const candidates=current&&searched&&!stale?findCandidates(S,teacher,current,mode,dates):[],proposals=chosen.filter(s=>selected[slotKey(s)]).map(s=>({slot:s,...selected[slotKey(s)]}));
 const issues=proposalIssues(S,teacher,proposals,mode,dates),complete=proposals.length===chosen.length&&chosen.length>0&&!issues.length&&!stale&&searched;
 const reset=()=>{setSearched(false);setSelected({});setActive('');setExpanded('');setStep(1)};
 const change=(setter,value)=>{setter(value);setPicked([]);reset()};
 const search=()=>{setSnapshot(signature);setSelected({});setSearched(true);setActive(slotKey(chosen[0]));setQuery('');goStep(2)};
 const print=()=>{if(!complete){st('กรุณาเลือกให้ครบและแก้รายการที่ต้องตรวจสอบก่อน','error');return}const w=window.open('','_blank');if(!w){st('กรุณาอนุญาตหน้าต่างพิมพ์','error');return}w.document.write(proposalHTML(S,teacher,proposals,mode,reason,ay,sh));w.document.close();w.addEventListener('load',()=>w.print(),{once:true});if(w.document.readyState==='complete')w.print()};
 return <div className="swap-workbench" ref={top} tabIndex={-1}><nav className="swap-steps" aria-label="ขั้นตอนแลกคาบ">{['เลือกคาบ','เลือกคู่แลก','ตรวจและพิมพ์'].map((label,i)=><button key={label} aria-current={step===i+1?'step':undefined} disabled={i>0&&!searched||i===2&&!complete} onClick={()=>goStep(i+1)}><b>{i+1}</b>{label}</button>)}</nav><p className="swap-step-help">{step===1?'เริ่มจากค้นหาครู เลือกวันที่ แล้วแตะคาบที่ต้องการแลก':step===2?'เลือกคาบที่จะจัดให้ แล้วเลือกครูและคาบสอนคืนทีละรายการ':'ตรวจทั้งคาบที่ขอแลกและคาบสอนคืนก่อนพิมพ์'}</p>

  <div className="swap-columns"><section className="swap-request" hidden={step!==1}><h3><i>1</i> ระบุคาบที่ต้องการ</h3><div className="teacher-field"><span>ครูผู้ขอแลก</span><TeacherPicker teachers={S.teachers} value={teacher} onChange={v=>change(setTeacher,v)}/></div><div className="swap-date-fields"><label>วันที่เริ่ม<DateField label="วันที่เริ่ม" value={from} onChange={v=>change(setFrom,v)}/></label><label>ถึงวันที่ (ถ้ามี)<DateField label="ถึงวันที่" min={from} value={to} onChange={v=>change(setTo,v)}/></label></div><label>เหตุผล<select value={reason} onChange={e=>setReason(e.target.value)}>{['ติดธุระ','ลาป่วย','ลากิจ','ไปราชการ','อบรม','อื่น ๆ'].map(x=><option key={x}>{x}</option>)}</select></label>{from&&!dates.length&&<p className="swap-warning">เลือกช่วงวันที่ถูกต้อง ไม่เกิน 31 วัน และมีวันจันทร์–ศุกร์</p>}
   <div className="swap-selection-head"><b>คาบตามวันที่เลือก ({slots.length})</b><button disabled={!slots.length} onClick={()=>{setPicked(slots.filter(s=>mode!=='swap'||(!s.coTeacherIds.length&&!S.locks?.[s.key]&&(S.schedule[s.key]||[]).length===1)).map(slotKey));reset()}}>เลือกทั้งหมด</button></div><SevenPicker dates={dates} slots={slots} picked={picked} mode={mode} S={S} onToggle={k=>{setPicked(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k]);reset()}}/><button className="swap-primary swap-full" disabled={!chosen.length} onClick={search}>ถัดไป · เลือกคู่แลก ({chosen.length} คาบ)</button>
  </section><section className="swap-match" hidden={step!==2}><h3><i>2</i> เปรียบเทียบและเลือกครู</h3>{!searched?<div className="swap-empty large"><b>เริ่มจากเลือกคาบในขั้นตอนที่ 1</b><p>ระบบตรวจคาบสอนและเวลาที่ทับกัน รวมถึงประชุมและคาบล็อกที่บันทึกไว้</p></div>:stale?<div className="swap-warning">ข้อมูลตารางเปลี่ยนแล้ว กรุณากดค้นหาใหม่ก่อนเลือกหรือพิมพ์</div>:<><div className="swap-active-slots">{chosen.map(s=><button key={slotKey(s)} onClick={()=>{setActive(slotKey(s));setQuery('');setExpanded('')}} aria-pressed={slotKey(s)===slotKey(current)} className={slotKey(s)===slotKey(current)?'active':''}><strong>{s.day} {thaiDate(s.date)}</strong><b>คาบ {s.period} · {s.time}</b><span>{s.subjectName} · {s.roomName}</span><small>{selected[slotKey(s)]?'✓ เลือกคู่แลกแล้ว':'รอเลือกคู่แลก'}</small></button>)}</div>{current&&<div className="swap-current"><span>กำลังจัดให้</span><b>{current.subjectName} · {current.roomName}</b><small>{current.day} {thaiDate(current.date)} · {current.time}</small></div>}<details className="swap-extra"><summary>เกณฑ์ภาระการสอน</summary><label className="load-limit">เตือนเมื่อเกิน (คาบ/วัน)<input type="number" min="1" max="7" value={dailyLimit} onChange={e=>setDailyLimit(Math.max(1,Math.min(7,+e.target.value||6)))}/></label></details><div className="swap-candidate-tools"><input aria-label="ค้นหาครูที่ว่าง" placeholder="ค้นหาชื่อครูที่ว่าง…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{candidates.length} คนผ่านเงื่อนไขเวลา</span></div>
    {!candidates.length&&<div className="swap-empty">ไม่พบคู่แลกที่ว่างทั้งสองฝั่งในช่วงก่อนวันแลก 14 วัน ถึงหลังวันแลก 28 วัน กรุณาเลือกคาบอื่น</div>}
    {candidates.filter(c=>`${c.teacher.firstName} ${c.teacher.lastName}`.includes(query.trim())).map(c=>{const k=slotKey(current),choice=selected[k],isSelected=choice?.candidate.teacher.id===c.teacher.id;return <article className={'swap-candidate '+(isSelected?'chosen':'')} key={slotKey(current)+c.teacher.id}><header><div><b>{c.teacher.prefix}{c.teacher.firstName} {c.teacher.lastName}</b><ColorBadge item={S.depts.find(d=>d.id===c.teacher.departmentId)}/></div><span>{c.load} คาบ / สัปดาห์</span></header><p className="candidate-reason">{c.reason}</p>{isSelected&&choice.back&&<p className="chosen-return"><b>สอนคืน {thaiDate(choice.back.date)} · คาบ {choice.back.period}</b><br/>{choice.back.subjectName} · {choice.back.roomName}</p>}<button className={isSelected?"swap-primary":""} aria-expanded={expanded===c.teacher.id} onClick={()=>setExpanded(expanded===c.teacher.id?'':c.teacher.id)}>{isSelected?'✓ เลือกคู่แลกแล้ว · แก้ไข':'เลือกครูคนนี้ · ดูคาบสอนคืน'}</button>{expanded===c.teacher.id&&<div className="candidate-choice"><div className="swap-candidate-bottom">{<ReturnCards candidate={c} choice={choice} S={S} current={current} limit={dailyLimit} proposals={proposals} onChoose={back=>setSelected(p=>({...p,[k]:{candidate:c,back}}))}/>}</div><details className="swap-extra"><summary>ดูผลต่อภาระครูและตารางหลังแลก</summary><LoadImpact mode={mode} S={S} candidate={c} current={current} back={isSelected?choice.back:null} limit={dailyLimit} proposals={proposals}/></details></div>}</article>})}
   </>}{!!issues.length&&<div className="swap-warning" role="alert">{issues.join(" · ")}</div>}<div className="swap-next"><button onClick={()=>goStep(1)}>← กลับไปเลือกคาบ</button><span>เลือกคู่แลกแล้ว {proposals.length} / {chosen.length} คาบ</span>{complete?<button className="swap-primary" onClick={()=>goStep(3)}>ถัดไป · ตรวจและพิมพ์</button>:<button disabled={!chosen.some(s=>!selected[slotKey(s)])} onClick={()=>{const next=chosen.find(s=>!selected[slotKey(s)]);if(next){setActive(slotKey(next));setExpanded('');setQuery('');top.current?.scrollIntoView({block:'start',behavior:'smooth'})}}}>ไปคาบที่ยังไม่ได้เลือกคู่แลก</button>}</div></section></div>
  <section className="swap-review" hidden={step!==3}><h3><i>3</i> ตรวจข้อเสนอก่อนพิมพ์ <small>{proposals.length} / {chosen.length} คาบ</small></h3>{proposals.length?<div className="swap-review-list">{proposals.map(p=><div key={slotKey(p.slot)}><span><b>{thaiDate(p.slot.date)} · คาบ {p.slot.period} · {p.slot.roomName}</b><small>{p.slot.subjectName}</small></span><span><b>{p.candidate.teacher.firstName} {p.candidate.teacher.lastName}</b><small>{p.back?`ผู้ขอสอนคืน ${thaiDate(p.back.date)} · คาบ ${p.back.period} · ${p.back.time} · ห้อง ${p.back.roomName}`:'ยังไม่ได้เลือกคาบสอนคืน'}</small></span><button onClick={()=>setSelected(s=>{const n={...s};delete n[slotKey(p.slot)];return n})}>นำออก</button></div>)}</div>:<p className="swap-note">ยังไม่มีรายการที่เลือก</p>}{!!issues.length&&<div className="swap-warning" role="alert">{issues.join(' · ')}</div>}<footer><button onClick={()=>goStep(2)}>← แก้ไขคู่แลก</button><p>ตรวจวันหยุด การลาของครูผู้รับงาน และยืนยันกับผู้เกี่ยวข้องก่อนใช้ข้อเสนอ<br/>รายการนี้ยังไม่บันทึกเป็นประวัติหรือเปลี่ยนตารางหลัก</p><button className="swap-primary" disabled={!complete} onClick={print}>ตรวจครบแล้ว · พิมพ์ / บันทึก PDF</button></footer></section>
 </div>
}
