import DateField from './DateField.jsx';
import {SevenPicker,LoadImpact,ReturnCards,thaiDate} from './SwapCards.jsx';
import React,{useState} from 'react';
import {datesBetween,requestedSlots,slotKey,findCandidates,proposalIssues,proposalHTML} from './swap-model.mjs';
import ColorBadge from './ColorBadge.jsx';

export default function SwapWorkbench({S,st,ay,sh}){
 const mode='swap';
 const [dailyLimit,setDailyLimit]=useState(6);
 const [teacher,setTeacher]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[reason,setReason]=useState('ติดธุระ'),[picked,setPicked]=useState([]),[active,setActive]=useState(''),[selected,setSelected]=useState({}),[searched,setSearched]=useState(false),[snapshot,setSnapshot]=useState(''),[query,setQuery]=useState('');
 const signature=JSON.stringify([S.schedule,S.teachers,S.meetings,S.locks,S.assigns,S.periodConfigs,S.subjects,S.rooms,S.roles]),stale=searched&&signature!==snapshot;
 const dates=datesBetween(from,to||from),slots=requestedSlots(S,teacher,from,to),chosen=slots.filter(s=>picked.includes(slotKey(s))),current=chosen.find(s=>slotKey(s)===active)||chosen[0];
 const candidates=current&&searched&&!stale?findCandidates(S,teacher,current,mode,dates):[],proposals=chosen.filter(s=>selected[slotKey(s)]).map(s=>({slot:s,...selected[slotKey(s)]}));
 const issues=proposalIssues(S,teacher,proposals,mode,dates),complete=proposals.length===chosen.length&&chosen.length>0&&!issues.length&&!stale&&searched;
 const reset=()=>{setSearched(false);setSelected({});setActive('')};
 const change=(setter,value)=>{setter(value);setPicked([]);reset()};
 const search=()=>{setSnapshot(signature);setSelected({});setSearched(true);setActive(slotKey(chosen[0]));setQuery('')};
 const print=()=>{if(!complete){st('กรุณาเลือกให้ครบและแก้รายการที่ต้องตรวจสอบก่อน','error');return}const w=window.open('','_blank');if(!w){st('กรุณาอนุญาตหน้าต่างพิมพ์','error');return}w.document.write(proposalHTML(S,teacher,proposals,mode,reason,ay,sh));w.document.close();w.addEventListener('load',()=>w.print(),{once:true});if(w.document.readyState==='complete')w.print()};
 return <div className="swap-workbench"><div className="swap-intro"><div><h2>แลกคาบสอน</h2><p>เลือกคาบที่ขอแลก → เลือกคู่แลกและคาบสอนคืน → ตรวจรายละเอียดก่อนพิมพ์</p></div><span className="swap-draft">ข้อเสนอ · ยังไม่เปลี่ยนตารางหลัก</span></div>

  <div className="swap-columns"><section className="swap-request"><h3><i>1</i> ระบุคาบที่ต้องการ</h3><label>ครูผู้ขอแลก<select value={teacher} onChange={e=>change(setTeacher,e.target.value)}><option value="">เลือกครู</option>{S.teachers.map(t=><option key={t.id} value={t.id}>{t.prefix}{t.firstName} {t.lastName}</option>)}</select></label><div className="swap-date-fields"><label>วันที่เริ่ม<DateField label="วันที่เริ่ม" value={from} onChange={v=>change(setFrom,v)}/></label><label>ถึงวันที่ (ถ้ามี)<DateField label="ถึงวันที่" value={to} onChange={v=>change(setTo,v)}/></label></div><label>เหตุผล<select value={reason} onChange={e=>setReason(e.target.value)}>{['ติดธุระ','ลาป่วย','ลากิจ','ไปราชการ','อบรม','อื่น ๆ'].map(x=><option key={x}>{x}</option>)}</select></label>{from&&!dates.length&&<p className="swap-warning">เลือกช่วงวันที่ถูกต้อง ไม่เกิน 31 วัน และมีวันจันทร์–ศุกร์</p>}
   <div className="swap-selection-head"><b>คาบตามวันที่เลือก ({slots.length})</b><button disabled={!slots.length} onClick={()=>{setPicked(slots.filter(s=>mode!=='swap'||(!s.coTeacherIds.length&&!S.locks?.[s.key]&&(S.schedule[s.key]||[]).length===1)).map(slotKey));reset()}}>เลือกทั้งหมด</button></div><SevenPicker dates={dates} slots={slots} picked={picked} mode={mode} S={S} onToggle={k=>{setPicked(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k]);reset()}}/><button className="swap-primary swap-full" disabled={!chosen.length} onClick={search}>ค้นหาครูให้ {chosen.length} คาบ</button>
  </section><section className="swap-match"><h3><i>2</i> เปรียบเทียบและเลือกครู</h3>{!searched?<div className="swap-empty large"><b>เริ่มจากเลือกคาบทางซ้าย</b><p>ระบบตรวจคาบสอนและเวลาที่ทับกัน รวมถึงประชุมและคาบล็อกที่บันทึกไว้</p></div>:stale?<div className="swap-warning">ข้อมูลตารางเปลี่ยนแล้ว กรุณากดค้นหาใหม่ก่อนเลือกหรือพิมพ์</div>:<><div className="swap-active-slots">{chosen.map(s=><button key={slotKey(s)} onClick={()=>{setActive(slotKey(s));setQuery('')}} aria-pressed={slotKey(s)===slotKey(current)} className={slotKey(s)===slotKey(current)?'active':''}><strong>{s.day} {thaiDate(s.date)}</strong><b>คาบ {s.period} · {s.time}</b><span>{s.subjectName} · {s.roomName}</span><small>{selected[slotKey(s)]?'✓ เลือกคู่แลกแล้ว':'รอเลือกคู่แลก'}</small></button>)}</div>{current&&<div className="swap-current"><span>กำลังจัดให้</span><b>{current.subjectName} · {current.roomName}</b><small>{current.day} {thaiDate(current.date)} · {current.time}</small></div>}<label className="load-limit">เตือนเมื่อเกิน (คาบ/วัน)<input type="number" min="1" max="7" value={dailyLimit} onChange={e=>setDailyLimit(Math.max(1,Math.min(7,+e.target.value||6)))}/></label><div className="swap-candidate-tools"><input aria-label="ค้นหาครูที่ว่าง" placeholder="ค้นหาชื่อครูที่ว่าง…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{candidates.length} คนผ่านเงื่อนไขเวลา</span></div><p className="swap-note">เรียงตามงานมอบหมายวิชา → กลุ่มสาระ → ห้องที่เคยสอน → ภาระน้อยกว่า การจัดอันดับไม่ใช่การรับรองความเหมาะสมในการสอน</p>
    {!candidates.length&&<div className="swap-empty">ไม่พบคู่แลกที่ว่างทั้งสองฝั่งในช่วงก่อนวันแลก 14 วัน ถึงหลังวันแลก 28 วัน กรุณาเลือกคาบอื่น</div>}
    {candidates.filter(c=>`${c.teacher.firstName} ${c.teacher.lastName}`.includes(query.trim())).map(c=>{const k=slotKey(current),choice=selected[k],isSelected=choice?.candidate.teacher.id===c.teacher.id;return <article className={'swap-candidate '+(isSelected?'chosen':'')} key={c.teacher.id}><header><div><b>{c.teacher.prefix}{c.teacher.firstName} {c.teacher.lastName}</b><ColorBadge item={S.depts.find(d=>d.id===c.teacher.departmentId)}/></div><span>{c.load} คาบ / สัปดาห์</span></header><div className="swap-candidate-bottom"><span>{c.reason}</span>{<ReturnCards candidate={c} choice={choice} S={S} current={current} limit={dailyLimit} proposals={proposals} onChoose={back=>setSelected(p=>({...p,[k]:{candidate:c,back}}))}/>}</div><LoadImpact mode={mode} S={S} candidate={c} current={current} back={isSelected?choice.back:null} limit={dailyLimit} proposals={proposals}/></article>})}
   </>}</section></div>
  <section className="swap-review"><h3><i>3</i> ตรวจข้อเสนอก่อนพิมพ์ <small>{proposals.length} / {chosen.length} คาบ</small></h3>{proposals.length?<div className="swap-review-list">{proposals.map(p=><div key={slotKey(p.slot)}><span><b>{thaiDate(p.slot.date)} · คาบ {p.slot.period} · {p.slot.roomName}</b><small>{p.slot.subjectName}</small></span><span><b>{p.candidate.teacher.firstName} {p.candidate.teacher.lastName}</b><small>{p.back?`สอนคืน ${thaiDate(p.back.date)} · คาบ ${p.back.period}`:'ยังไม่ได้เลือกคาบสอนคืน'}</small></span><button onClick={()=>setSelected(s=>{const n={...s};delete n[slotKey(p.slot)];return n})}>นำออก</button></div>)}</div>:<p className="swap-note">ยังไม่มีรายการที่เลือก</p>}{!!issues.length&&<div className="swap-warning" role="alert">{issues.join(' · ')}</div>}<footer><p>ตรวจวันหยุด การลาของครูผู้รับงาน และยืนยันกับผู้เกี่ยวข้องก่อนใช้ข้อเสนอ<br/>รายการนี้ยังไม่บันทึกเป็นประวัติหรือเปลี่ยนตารางหลัก</p><button className="swap-primary" disabled={!complete} onClick={print}>ตรวจครบแล้ว · พิมพ์ / บันทึก PDF</button></footer></section>
 </div>
}
