import ColorBadge from './ColorBadge.jsx';
import React, {useState,useMemo} from 'react';
import {Glyph} from './Workspace.jsx';
import {teacherLoad} from './model.mjs';
export default function TeacherDirectory({S,onAdd,onEdit,onDelete,onImport,onExport,onTemplate}) {
 const [query,setQuery]=useState(''),[department,setDepartment]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1);
 const rows=useMemo(()=>S.teachers.map(t=>({...t,load:teacherLoad(S,t.id)})),[S]);
 const filtered=rows.filter(t=>(!department||t.departmentId===department)&&(`${t.prefix}${t.firstName} ${t.lastName} ${t.teacherCode||''}`.toLowerCase().includes(query.trim().toLowerCase()))&&(!status||(status==='remaining'&&t.load<(t.totalPeriods||0))||(status==='over'&&t.load>(t.totalPeriods||0))||(status==='full'&&t.load===(t.totalPeriods||0))));
 const pageCount=Math.max(1,Math.ceil(filtered.length/10)),current=Math.min(page,pageCount),visible=filtered.slice((current-1)*10,current*10);
 const update=(fn)=>e=>{fn(e.target.value);setPage(1)};
 return <>
  <div className="directory-actions"><div><button className="secondary" onClick={onImport}><Glyph name="download" size={16}/> นำเข้า Excel</button><button className="text-button" onClick={onTemplate}>ดาวน์โหลดแบบฟอร์ม</button></div><div><button className="secondary" onClick={onExport}><Glyph name="download" size={16}/> ส่งออก</button><button className="primary" onClick={onAdd}><Glyph name="plus" size={16}/> เพิ่มครู</button></div></div>
  <div className="summary-strip"><span><strong>{rows.length}</strong> ครูทั้งหมด</span><span><strong>{rows.filter(t=>t.load<(t.totalPeriods||0)).length}</strong> ยังลงคาบไม่ครบ</span><span><strong>{rows.filter(t=>t.load>(t.totalPeriods||0)).length}</strong> ลงคาบเกินภาระ</span></div>
  <div className="toolbar"><label className="search-box"><Glyph name="search" size={17}/><input aria-label="ค้นหาชื่อหรือรหัสครู" placeholder="ค้นหาชื่อ หรือรหัสครู…" value={query} onChange={update(setQuery)}/></label><select aria-label="กรองกลุ่มสาระ" value={department} onChange={update(setDepartment)}><option value="">ทุกกลุ่มสาระ</option>{S.depts.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select aria-label="กรองภาระสอน" value={status} onChange={update(setStatus)}><option value="">ทุกสถานะภาระสอน</option><option value="remaining">ยังลงคาบไม่ครบ</option><option value="full">ลงคาบครบแล้ว</option><option value="over">ลงคาบเกินภาระ</option></select><span className="right">พบ {filtered.length} คน</span></div>
  <section className="surface table-surface"><table className="modern-table"><thead><tr>{['ชื่อครู / รหัส','กลุ่มสาระ','ภาระสอน / สัปดาห์','ลงตารางแล้ว','สถานะ','จัดการ'].map(s=><th key={s} scope="col">{s}</th>)}</tr></thead><tbody>{visible.map(t=>{const target=Number(t.totalPeriods)||0,remain=target-t.load;return <tr key={t.id}><td><div className="teacher-name"><span className="avatar">{t.firstName?.[0]}</span><span><strong>{t.prefix}{t.firstName} {t.lastName}</strong><small>{t.teacherCode||'ยังไม่มีรหัสครู'}</small></span></div></td><td><ColorBadge item={S.depts.find(d=>d.id===t.departmentId)}/></td><td><strong>{target}</strong> <span className="muted">คาบ</span></td><td>{t.load}<span className="load-track"><i style={{width:Math.min(100,target?t.load/target*100:0)+'%'}}/></span></td><td><span className={'pill '+(remain<0?'red':remain>0?'amber':'load-complete')}>{remain<0?`เกิน ${-remain} คาบ`:remain>0?`เหลือ ${remain} คาบ`:'ครบตามภาระ'}</span></td><td><button className="icon-button" onClick={()=>onEdit(t)} aria-label={`แก้ไข ${t.firstName}`} title="แก้ไขข้อมูลครู"><Glyph name="edit" size={15}/></button><button className="icon-button" onClick={()=>onDelete(t)} aria-label={`ลบ ${t.firstName}`} title="ลบครู"><Glyph name="close" size={15}/></button></td></tr>})}</tbody></table>{!filtered.length&&<div className="empty-message">{rows.length?'ไม่พบครูที่ตรงกับตัวกรอง ลองค้นหาใหม่หรือเลือกทุกสถานะ':'ยังไม่มีข้อมูลครู เริ่มด้วยปุ่ม “เพิ่มครู”'}</div>}<div className="table-footer"><span>{filtered.length?`${(current-1)*10+1}–${Math.min(current*10,filtered.length)} จาก ${filtered.length} คน`:'0 คน'}</span><div><button disabled={current<=1} onClick={()=>setPage(current-1)}>ก่อนหน้า</button><span> {current} / {pageCount} </span><button disabled={current>=pageCount} onClick={()=>setPage(current+1)}>ถัดไป</button></div></div></section>
 </>;
}
