import assert from 'node:assert/strict';
import {makeTemplate,entriesAt,printDocument,templateIssues,migrateLegacy} from '../src/renovation/print-model.mjs';
import {departmentTone,levelTone} from '../src/renovation/colors.mjs';
const S={levels:[{id:'l1',name:'ป.1',assemblyDay:'จันทร์'},{id:'l2',name:'ม.4'}],rooms:[{id:'room_with_underscores',name:'ป.1/1',levelId:'l1'},{id:'r2',name:'ม.4/1',levelId:'l2'}],depts:[{id:'d',name:'คณิตศาสตร์'}],subjects:[{id:'s1',name:'คณิต <script>alert(1)</script>',departmentId:'d'},{id:'s2',name:'ภาษาไทย'}],teachers:[{id:'t1',firstName:'ครูหนึ่ง'},{id:'t2',firstName:'ครูร่วม'}],schedule:{'room_with_underscores_จันทร์_6':[{id:'e1',subjectId:'s1',teacherId:'t1',coTeacherIds:['t2']},{id:'e2',subjectId:'s2',teacherId:'t2'}],'r2_จันทร์_6':[{id:'e3',subjectId:'s1',teacherId:'t1'}]},printPeriodConfigs:{room_with_underscores:{periods:[{id:6,time:'13.50–14.40'}]},r2:{periods:[{id:6,time:'14.00–14.50'}]}}};
const cfg={periods:[{id:6,time:'13.50–14.40'}],breaks:[{afterPid:0,label:'08.00–08.30'}]};
const t=makeTemplate(S.levels[0],cfg);
assert.equal(entriesAt(S,'room',S.rooms[0].id,'จันทร์',6).length,2,'all parallel subjects are retained');
assert.equal(entriesAt(S,'teacher','t1','จันทร์',6).length,2,'multiple rooms retained');
assert.equal(entriesAt(S,'teacher','t2','จันทร์',6).length,2,'co-teacher included');
assert.equal(entriesAt(S,'room','r2','อังคาร',6).length,0);
assert.equal(templateIssues(t,S,'room',S.rooms[0].id).length,0);
assert.ok(templateIssues({...t,days:['อังคาร']},S,'room',S.rooms[0].id).some(s=>s.includes('ถูกซ่อน')));
assert.ok(templateIssues({...t,columns:[]},S,'room',S.rooms[0].id).length);
assert.ok(templateIssues({...t,columns:[...t.columns,t.columns[1]]},S,'room',S.rooms[0].id).some(s=>s.includes('คาบซ้ำ')));
const before=JSON.stringify(S);const teacher=makeTemplate(null,cfg);
let html=printDocument([{template:teacher,type:'teacher',id:'t1'}],S,{year:2569,semester:2},{schoolName:'A&B'});
assert.ok(html.includes('13.50–14.40')&&html.includes('14.00–14.50'),'actual room division times');
assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('A&amp;B'));
assert.ok(html.includes('ป.1/1')&&html.includes('ม.4/1'));
html=printDocument([{template:{...t,columns:t.columns.map(c=>({...c,show:true}))},type:'room',id:S.rooms[0].id},{template:{...t,paper:'A3',orientation:'portrait'},type:'room',id:'r2'}],S);
assert.ok(html.includes('เข้าหอประชุม'));assert.ok(html.includes('@page sheet1{size:A3 portrait'));assert.ok(html.includes('ครูร่วม'));assert.equal(JSON.stringify(S),before,'printing does not mutate timetable');
const migrated=migrateLegacy({columns:[{type:'day'},{type:'period',periodId:6,show:true,timeLabel:'14.00'}],cellRows:[{field:'subject_code'}]},t);assert.equal(migrated.columns.length,1);assert.equal(migrated.columns[0].time,'14.00');
assert.deepEqual(departmentTone({id:'d',name:'คณิตศาสตร์'}),departmentTone({id:'changed',name:'คณิตศาสตร์'}));assert.notDeepEqual(departmentTone({name:'คณิตศาสตร์'}),departmentTone({name:'ภาษาไทย'}));assert.notDeepEqual(levelTone({name:'ม.4'}),levelTone({name:'ม.5'}));
console.log('PASS print studio: parallel lessons, co-teachers, mixed grade times, hidden data validation, activity days, escaping, multiple paper sizes, legacy migration, stable colors');
